### ISSUE TITLE
Linter activation

### ISSUE THREAD

**Issue by ricardofbarros** [steelbrain/package-deps#8]
I don't know if this is a issue of this package or [atom-community/linter](https://github.com/atom-community/linter). 

I know you are using `atom.packages.enablePackage()` but to linters fully work you need to restart/reload atom. I tested with `linter-js-standard` and `linter-ruby`.

**Comment by ricardofbarros** [comment]
But my guess is that this is [atom-community/linter](https://github.com/atom-community/linter) issue.

**Comment by steelbrain** [comment]
Okay, so uninstall linter, get it installed using `package-deps` and then do `atom.packages.activatePackage('linter')` and then do `atom.packages.getActivePackage('linter')` and let me know what you see in the console

**Comment by ricardofbarros** [comment]
Hmm it returns undefined the `atom.packages.getActivePackage('linter')` but if I call manually the `atom.packages.activatePackage('linter')` it works :/

**Comment by ricardofbarros** [comment]
ah okay different methods `atom.packages.activatePackage('linter')` and `atom.packages.enablePackage()`

**Comment by steelbrain** [comment]
Fixed by https://github.com/steelbrain/package-deps/commit/37dbc3447be7045564c4e67d90fa435c790947c6

**Comment by ricardofbarros** [comment]
Great! :+1:

**Comment by steelbrain** [comment]
The fix is in release `atom-package-deps@2.0.4`

**Comment by ricardofbarros** [comment]
Still doesn't work I think you need also `atom.packages.activatePackage(name)` on this [line](https://github.com/steelbrain/package-deps/blob/master/lib/main.js#L50).

**Comment by steelbrain** [comment]
the new fix is in `2.0.5` and in https://github.com/steelbrain/package-deps/commit/ccc2aadd51096b2ead75e2ef38dbdc2d4007b3bd
sorry about not fixing it all in one release. I am watching a movie so rushing through the bug hunting process

**Comment by ricardofbarros** [comment]
No worries man :smile:, please watch your movie I could definitely wait, now I feel guilty :sob: Thanks once again.
